sudo ln -sfn $PWD/full-assemble.sh /usr/local/bin/full-assemble
sudo ln -sfn $PWD/assemble.sh  /usr/local/bin/assemble
sudo ln -sfn $PWD/git-updatepr.sh /usr/local/bin/git-updatepr
sudo ln -sfn $PWD/git-newpr.sh  /usr/local/bin/git-newpr
sudo ln -sfn $PWD/installapp.sh /usr/local/bin/installapp
sudo ln -sfn $PWD/gitlog.sh /usr/local/bin/gitlog
sudo ln -sfn $PWD/code.sh /usr/local/bin/code
sudo ln -sfn $PWD/git-amendpr.sh /usr/local/bin/git-amendpr
sudo ln -sfn $PWD/git-reset-main.sh /usr/local/bin/git-reset-main
sudo ln -sfn $PWD/git-prs.sh /usr/local/bin/git-prs
sudo ln -sfn $PWD/git-review.sh /usr/local/bin/git-review
sudo ln -sfn $PWD/git-merge-pr.sh /usr/local/bin/git-merge-pr
sudo ln -sfn $PWD/squash-commits.go /usr/local/bin/squash-commits.go
sudo ln -sfn $PWD/git-get-commit-branch.sh /usr/local/bin/git-get-commit-branch
