#!/bin/bash
 
set -uo pipefail

trap ctrl_c INT

# Kill entire script, not just currently running command, and also avoid say command on ctrl-c
say_pid=""
function ctrl_c() {
    if [[ $say_pid ]]; then
        kill $say_pid
    fi
    exit 1
}


# Whether script should be silent (true), or use say (false). "-s" flag.
silent="false"

if [[ "${1-}" == "--silent" || "${1-}" == "-s" ]]; then
  silent="true"
  shift
fi


# Note: lint is omitted as it often hangs the process during configuration.

# Run compileCiUnitTest first as the full assemble command has not been able to run
# recently without crashing gradle unless it has a huge amount of memory allocated.

set -x # show executing lines

./gradlew compileCiUnitTest \
    "$@"

retVal=$?

if [ $retVal -ne 0 ]; then
    if [[ "$silent" == "false" ]]; then
        say could not compile unit tests &
        say_pid=$!
    fi
    exit $retVal
fi

./gradlew assembleInternalDebug \
    compileReleaseUnitTestSources \
    compileInternalDebugUnitTestSources \
    app:assembleInternalDebugAndroidTest \
    detekt \
    assertAllowedModuleDependencies \
    assertMaxHeight \
    assembleReleaseAndroidTest \
    spotlessCheck \
    :app:dependencyGuard \
    "$@"

retVal=$?

set +x

if [ $retVal -eq 0 ]; then
    if [[ "$silent" == "false" ]]; then
        say assemble complete &
        say_pid=$!
    fi
else
    if [[ "$silent" == "false" ]]; then
        say not assembled &
        say_pid=$!
    fi
fi
exit $retVal
