#!/bin/bash

# Warning: Either use command line build or IDE build but avoid mixing both during your workflow, 
# as it can slow down build times
# See https://issuetracker.google.com/issues/164145066
# Note: use bash instead of golang to propertly display the rich text output of ./gradle.

set -uo pipefail

trap ctrl_c INT

# Kill entire script, not just currently running command, and also avoid say command on ctrl-c
say_pid=""

function ctrl_c() {
    if [[ $say_pid ]]; then
        kill $say_pid
    fi
    exit 1
}

# Whether script should be silent (true), or use say (false). "-s" flag.
silent="false"

if [[ "${1-}" == "--silent" || "${1-}" == "-s" ]]; then
  silent="true"
  shift
fi

set -x # show executing lines

./gradlew assembleInternalDebug "$@"
    
retVal=$?

set +x

if [ $retVal -ne 0 ]; then
    if [[ "$silent" == "false" ]]; then
        say not assembled &
        say_pid=$!
    fi
    exit $retVal
fi

silentArgs=""
if [[ "$silent" == "true" ]]; then
    silentArgs=-s
fi
install-apk $silentArgs
retVal=$?
exit $retVal
